### PR TITLE
Add csv of Data dictionary for Nat Geo 1986

### PR DESCRIPTION
**Pull request by joelmainland**
We can delete the xlsx version as far as I'm concerned.

### CODE REVIEW

**Comment by joelmainland** [comment]
Not sure I did this pull request properly. I just wanted to add the datadictionary.csv file, the manifest updates have already been merged.

**Comment by rgerkin** [comment]
@joelmainland Is this just a .csv version of the .xlsx?  Is it because you want .csv for everything (I generally prefer it to but python pyrfume loads in .xlsx the same way as .csv).

**Comment by joelmainland** [comment]
Yep, this is primarily for the Codefest demo. It is much easier to get the web app to interact with csv files out of the box.

**Comment by joelmainland** [comment]
Yes, specifically because RStudioCloud natively reads csv and they need to be able to look at the data dictionary for the Perfume Codefest.

**Pull request merged**
